var hierarchy =
[
    [ "Argument", "structArgument.html", null ],
    [ "ArrayList", "structArrayList.html", null ],
    [ "BirthDeathCacheArray", "structBirthDeathCacheArray.html", null ],
    [ "BirthDeathCacheKey", "structBirthDeathCacheKey.html", null ],
    [ "BranchCuttingParam", "structBranchCuttingParam.html", null ],
    [ "CafeFamily", "structCafeFamily.html", null ],
    [ "CafeFamilyItem", "structCafeFamilyItem.html", null ],
    [ "CafeNode", "structCafeNode.html", null ],
    [ "CafeTree", "structCafeTree.html", null ],
    [ "CDParam", "structCDParam.html", null ],
    [ "change", "structchange.html", null ],
    [ "chooseln_cache", "structchooseln__cache.html", null ],
    [ "ConditionalDistribution", "classConditionalDistribution.html", null ],
    [ "coord", "structcoord.html", null ],
    [ "cross_validator", "classcross__validator.html", null ],
    [ "ctype", null, [
      [ "my_ctype", "classmy__ctype.html", null ]
    ] ],
    [ "CutBranch", "classCutBranch.html", null ],
    [ "ErrorMeasure", "structErrorMeasure.html", null ],
    [ "errormodel_args", "structerrormodel__args.html", null ],
    [ "ErrorStruct", "structErrorStruct.html", null ],
    [ "esterror_args", "structesterror__args.html", null ],
    [ "family_args", "structfamily__args.html", null ],
    [ "family_line_item", "structfamily__line__item.html", null ],
    [ "family_size_range", "structfamily__size__range.html", null ],
    [ "FMinSearch", "structFMinSearch.html", null ],
    [ "gene_family", "structgene__family.html", null ],
    [ "Globals", "classGlobals.html", null ],
    [ "GMatrix", "structGMatrix.html", null ],
    [ "hash_table", "structhash__table.html", null ],
    [ "hash_table_element", "structhash__table__element.html", null ],
    [ "input_values", "structinput__values.html", null ],
    [ "lambda_arg_base", "structlambda__arg__base.html", [
      [ "lambda_args", "structlambda__args.html", null ],
      [ "lambdamu_args", "structlambdamu__args.html", null ]
    ] ],
    [ "lambda_range", "structlambda__range.html", null ],
    [ "lhtest_args", "structlhtest__args.html", null ],
    [ "load_args", "structload__args.html", null ],
    [ "LRT2LParam", "structLRT2LParam.html", null ],
    [ "LRTParam", "structLRTParam.html", null ],
    [ "PnodeParam", "structPnodeParam.html", null ],
    [ "poisson_lambda", "structpoisson__lambda.html", null ],
    [ "posterior", "structposterior.html", null ],
    [ "probabilities", "structprobabilities.html", null ],
    [ "pvalue_args", "structpvalue__args.html", null ],
    [ "Report", "structReport.html", null ],
    [ "report_parameters", "structreport__parameters.html", null ],
    [ "roots", "structroots.html", null ],
    [ "runtime_error", null, [
      [ "io_error", "classio__error.html", null ]
    ] ],
    [ "square_matrix", "structsquare__matrix.html", null ],
    [ "streambuf", null, [
      [ "log_buffer", "classlog__buffer.html", null ]
    ] ],
    [ "String", "structString.html", null ],
    [ "tagANOVA", "structtagANOVA.html", null ],
    [ "tagANOVAResultElement", "structtagANOVAResultElement.html", null ],
    [ "tagCafeParam", "structtagCafeParam.html", null ],
    [ "tagHistogram", "structtagHistogram.html", null ],
    [ "tagLinkedListItem", "structtagLinkedListItem.html", null ],
    [ "tagMetapostConfig", "structtagMetapostConfig.html", null ],
    [ "tagPhylogenyNode", "structtagPhylogenyNode.html", null ],
    [ "tagTree", "structtagTree.html", null ],
    [ "tagTreeNode", "structtagTreeNode.html", null ],
    [ "tagVector", "structtagVector.html", null ],
    [ "to_lower", "structto__lower.html", null ],
    [ "tree_visualization", "classtree__visualization.html", [
      [ "ascii_visualization", "classascii__visualization.html", null ],
      [ "newick_visualization", "classnewick__visualization.html", null ],
      [ "svg_visualization", "classsvg__visualization.html", null ]
    ] ],
    [ "viterbi_args", "structviterbi__args.html", null ],
    [ "viterbi_parameters", "classviterbi__parameters.html", null ],
    [ "ViterbiParam", "structViterbiParam.html", null ]
];